### ISSUE TITLE
mongodb atlas not working

### ISSUE THREAD

**Issue by anthonycampbell** [share/sharedb-mongo#104]
Hello. I am not really sure where to post this question. If there is a better place I would love to be directed there. 

I have Sharedb working, but I would love persistent storage with my mongodb atlas. I am trying to use the sharedb-mongo adapter like this.

`var mongoDB = 'mongodb+srv://<user>:<password>@cluster0-hh67p.azure.mongodb.net/<collection>?retryWrites=true&w=majority';
var smdb = require('sharedb-mongo')(mongoDB, {mongoOptions: {useNewUrlParser: true, useUnifiedTopology: true}});`

I feel like it should be working because the url string I am connecting with works elsewhere in my app. Do I need a local mongodb?

**Comment by alecgibson** [comment]
What error are you getting? If you can get a working `MongoClient` elsewhere, you can pass that directly into `sharedb-mongo` instead of the connection string:

```
const mongodb = require('mongodb');
const db = require('sharedb-mongo')({mongo: function(callback) {
  mongodb.connect('mongodb://localhost:27017/test', callback);
}});
const backend = new ShareDB({db});
```

**Comment by anthonycampbell** [comment]
There is no error. The application continues as if I were using memory for storage, and my DB doesn't contain the created documents. Am I maybe not saving them properly? I guess I kind of figured that I didn't need to handle that, which I now think might have been dumb.

**Comment by alecgibson** [comment]
No, it's not dumb; the whole point of ShareDB is that it "saves" as you submit. Have you tried like in the above example, and passed in a valid `mongodb` client that you know works?

**Comment by anthonycampbell** [comment]
Hmm. The thing is I am using mongoose to connect elsewhere. Mongoose only requires the string to connect and that is working. I did try the same exact code that you posted except with the string value changed to the remote DB. Same thing is happening. I think I may be using sharedb incorrectly.

**Comment by anthonycampbell** [comment]
Does the collection need to exist before I can use it in a sharedb connection?

**Comment by anthonycampbell** [comment]
Right now I am doing this on the backend to create a document. 

`var doc = shareCon.get('subjects', 'newTables');
    doc.fetch(function(err) {
        if (err) throw err;
        if (doc.type === null) {
            doc.create({ tables: [{ title: null, fields: []}]});
        }
    });
    wssShare.on('connection', function(ws, req) {
        var stream = new WebSocketJSONStream(ws);
        backend.listen(stream);
    });`

I would imagine this document should appear somewhere in the db shortly after this happens if i am connected to the db correctly.

**Comment by alecgibson** [comment]
Pretty hard to say what's going on without any errors. I'd make sure you're correctly logging errors in all the callbacks (NB: `create` should have an error handling callback). Also try logging the contents of your `Doc` after `create` as a sense-check that it's actually at least been created in memory.

Also I can't remember off the top of my head, but it's possible that `doc.type` is `undefined` for an unitialised `Doc`? So maybe check `if (!doc.type)`?

**Comment by anthonycampbell** [comment]
I know something is working because: 

https://user-images.githubusercontent.com/10249255/103647417-22644600-4f10-11eb-95cd-62ab326dde52.mov

And when I reload the page the data is persistent, but when I restart the app the data is lost, which makes me believe it isnt saving to the DB

**Comment by anthonycampbell** [comment]
It is late for me now, and I have to sleep. I will look into the things you mentioned as soon as I can. I dunno how you feel about leaving issues open but I would love to keep this one open a while longer to give myself a fighting chance at beating this thing.

**Comment by anthonycampbell** [comment]
IT WORKS! I think I was being silly. I had this line: 
`var backend = new ShareDB({smdb});`

I changed it to this:
`var backend = new ShareDB({db: smdb});`

I think that I saw this somewhere:
`var backend = new ShareDB({db});`

and that made me think that I was okay doing what I did. As far as I can tell this resolves the issue. Thank you so much for your help! your response time was so fast. I attribute a good chunk of this victory to your presence. Thank you again. I will try to close this issue. If for some reason I cannot (i dunno, permissions or something) then you can feel free to close this if that helps you.

**Comment by alecgibson** [comment]
For reference, what you're talking about is [object destructuring][1]: modern JS magic, where your variable name must match the expected property name.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring
