### ISSUE TITLE
The problem of data storage

### ISSUE THREAD

**Issue by wangjianweiwei** [share/sharedb-mongo#112]
https://github.com/share/sharedb-mongo/blob/2287e66718537805eb326a8b600148ce9ff474f9/index.js#L219

If the `snapshot` is stored first, then the `op` is stored

What will happen?

**Comment by alecgibson** [comment]
I'm not sure I understand the question? In the function that you've pointed to, you can see that the op is written first.

**Comment by wangjianweiwei** [comment]
According the my understanding, it saved the op first and then the snapshot.
But if it saved the snapshot first and then the op, I would not need to consider that whether the op is saved.
So would it be a better way to do the thing ?

**Comment by alecgibson** [comment]
Why do you need to consider whether the op has been saved? Could you please provide a bit more context on what it is you're trying to achieve?

**Comment by wangjianweiwei** [comment]
```python
@dataclass
class Snapshot:
    _id: str
    snapshot: list
    head: int
    v: int = None
    operates: list = None

    async def commit(self, operate: "Operate"):
        """
        将`Snapshot`存入数据库

        :return:
        """
        v = await self.query_version(self._id)
        print(f"[冲突] 快照版本{self.v} op版本{v}")
        if self.v - v != 1:
            raise exceptions.CommitException("version error")

        query = {"_id": self._id, "v": v}
        update = {"$set": self.asdict()}
        
        # try commit snapshot
        res = await mongo[SnapshotTable].update_one(query, update)
        if not res.matched_count:
            raise exceptions.CommitException(f"Conflict, Retry commit")
        # commit op
        mongo[OperateLogTable].insert({"_id": self._id}, {"$push": {"operates": operate.asdict()}})
```

**Comment by alecgibson** [comment]
So you're trying rewrite the adapter in Python? Supporting that is beyond the scope of this library, unfortunately.

**Comment by wangjianweiwei** [comment]
Yes, I'm developing the editor collaborative project, using python. I'm currently learning some experience in sharedb, and I'm also using mongodb in the project.
