### ISSUE TITLE
metaOperators for mapReduce

### ISSUE THREAD

**Issue by kurtsergey** [share/sharedb-mongo#17]
I think `$mapReduce`, `$map`, `$reduce` should be included into `metaOperators`.
Now the query doesn't work if there is no optional `$query` parameter.

**Comment by avital** [comment]
Instead, in ShareDB 1.0 all mapReduce options will be placed directly into the `$mapReduce` property.

**Comment by avital** [comment]
Should be fixed as part of #33. Now the query format is `{$mapReduce: {map: ..., reduce, ..., /*optional*/ scope: ...}}`
