### ISSUE TITLE
Could you tell me more about "You should always use livedb to edit documents-- don't just edit them directly in mongo. You'll get weird behaviour if you do."

### ISSUE THREAD

**Issue by bitliner** [share/sharedb-mongo#19]
To avoid weird behaviour, and I need to edit a document using the `mongo` client, should I restart the shareJS after each update?

What you mean for weird behaviour? Inconsistent data? Some operation will not have effect?

My scenario is that 2 APIs are going to edit documents, one REST and one ShareJS. 
Should I assume that they can't live together, shoudn't I?

How to make them live together? Any suggestion?
Cannot I tell ShareJS  to refresh a document that is currently handling?

**Comment by nateps** [comment]
It is impossible for share to work if you edit the mongo documents directly. It will not create ops for the changes, and the whole way OT works is that it creates operations for each change. This will definitely break.
