### ISSUE TITLE
Don't add {_type: {$ne: null}} in Mongo queries unless necessary

### ISSUE THREAD

**Issue by avital** [share/sharedb-mongo#27]
ShareDB never deletes documents from the database -- instead, it removes all of the fields and sets the `_type` field to be null. More context can be found on [this mailing list thread](https://groups.google.com/d/msg/sharejs/ztbqawdmcGg/DxzSIKH3CwAJ).

The way ShareDB ensures queries don't see deleted documents is by adding an additional `type: {$ne: null}` filter to every query.

As pointed out in the mailing list thread linked to above, not all queries need to be modified in this way. To start, any query with `{foo: value}` with non-null `value` will never match deleted documents (that are empty other than the `_type` field). So those queries don't need to be modified.

This generalizes to additional classes of queries. Here’s a recursive description of queries that don’t need to be modified: In general, a query with `{foo: X}` doesn’t need to be modified if `X` is guaranteed to not match null or undefined. In addition to non-null values, the following clauses are guaranteed to not match null or undefined:
* `{$in: [A, B, C]}}` where all of A, B, C are non-null.
* `{$ne: null}`
* `{$exists: true}`
* `{$and: [A, B, C]}` where at least one of A, B, C is guaranteed to not match null
* `{$or: [A, B, C]}` where all of A, B, C are guaranteed to not match null
* `{$gt: ...}`, `{gte: ...}`, `{$lt: ...}`, `{$lte: ...}`

In addition, some queries that have `$and` or `$or` at the top-level don’t need to be modified:
* `{$and: [A, B, C]}`, where at least one of A, B, C are queries guaranteed to not match `{_type: null}`
* `{$or: [A, B, C]}`, where all of A, B, C are queries guaranteed to not match `{_type: null}`

There are more queries that can be optimized but they aren’t that common, e.g. ones using `$type` or bit-wise operators.

**Comment by avital** [comment]
cc @droganov

**Comment by droganov** [comment]
Hello Avital. Good to know you've let it go!

**Comment by avital** [comment]
Should be resolved now that #32 is merged. (Though a new release hasn't yet been published to NPM)
