### ISSUE TITLE
Reproduce 'richt text' example with sharedb-mongo adapter

### ISSUE THREAD

**Issue by sagacitysite** [share/sharedb-mongo#57]
Hi,

I currently try to reproduce the 'richt-text' sharedb example, but the doument should be stored in mongo using sharedb-mongo.

Whatever I try, the data is not stored in the database. I get no error, but nothing is stored.

Here is what I tried:

<pre><code>
var ShareDB = require('sharedb');
var richText = require('rich-text');
var sharedb = require('sharedb-mongo')('mongodb://127.0.0.1/test');

ShareDB.types.register(richText.type);
var backend = new ShareDB({sharedb});

function createDoc() {
    var connection = backend.connect();
    var doc = connection.get('examples', 'richtext');

    doc.fetch(function(err) {
        if (err) throw err;
        if (doc.type === null) {
            doc.create([{insert: 'Hi!'}], 'rich-text');
            return;
        }
        return;
    });
}
</code></pre>

where `createDoc()` is called somewhere.

Probably it is just a lack of understanding. Would be great if someone could give me a short hint what is probably wrong here.

**Comment by sagacitysite** [comment]
Ok, I found it. It's simply the key which is missing. The `backend` should be defined as:

`var backend = new ShareDB({ 'db': sharedb});`

and **not** as

`var backend = new ShareDB({sharedb});`

Would be nice if the readme could be updated.

**Comment by ericyhwang** [comment]
_Cleaning up old issues_

From what I can tell, the README has given the example as `new ShareDb({db})` since 2016:
https://github.com/share/sharedb-mongo/tree/v1.0.0-beta.2#usage
