### ISSUE TITLE
Tests fail because `m` property is missing in the MongoSnapshot

### ISSUE THREAD

**Issue by gkubisa** [share/sharedb-mongo#69]
- `if (meta) this.m = meta;` should be `this.m = meta || null;` [here](https://github.com/share/sharedb-mongo/blob/2d579ddb80781e987707076e932cd4e01ca066ef/index.js#L1224).
- `m: null` property is missing [here](https://github.com/share/sharedb-mongo/blob/2d579ddb80781e987707076e932cd4e01ca066ef/test/test_mongo.js#L356).

**Comment by alecgibson** [comment]
I raised a PR for this ages ago: https://github.com/share/sharedb-mongo/pull/67

**Comment by ericyhwang** [comment]
Got the fix merged and published as [sharedb@1.0.0-beta.6](https://github.com/share/sharedb-mongo/releases/tag/v1.0.0-beta.6), thanks for the ping!
