### ISSUE TITLE
Issues when connecting to ShareDB using MongoDB adapter

### ISSUE THREAD

**Issue by Alec-Aldrine-Lakra** [share/sharedb-mongo#81]
C:\Users\Alec\Desktop\Editor\editor\backend\node_modules\sharedb-mongo\index.js:80
    var collection = mongo.collection(collectionName);
                           ^
TypeError: mongo.collection is not a function

**Comment by alecgibson** [comment]
Can you please post your code?

**Comment by Alec-Aldrine-Lakra** [comment]
`var ShareDB = require('sharedb');
var richText = require('rich-text');
var WebSocket = require('ws');
var WebSocketJSONStream = require('@teamwork/websocket-json-stream');
ShareDB.types.register(richText.type);
const mongodb = require('mongodb');
const db = require('sharedb-mongo')({mongo: function(callback) {
  mongodb.connect('mongodb://localhost:27017/test',{useUnifiedTopology: true},callback);
}});
const backend = new ShareDB({db, disableDocAction: true, disableSpaceDelimitedActions: true});

createDoc();

// Create initial document then fire callback
function createDoc() {
  var connection = backend.connect();
  var doc = connection.get('examples', 'richtext'); //examples collection with id = 'richtext'
  doc.fetch(function(err) {
    if (err) throw err;
    if (doc.type === null) {
      doc.create([{insert: 'Hi!'}], 'rich-text', callback);
      return;
    }
  });
}`

> I

**Comment by alecgibson** [comment]
And which version of `mongodb` are you on? Note that technically you're [still meant to use the 2.x driver][1]

[1]: https://github.com/share/sharedb-mongo/issues/76

**Comment by Alec-Aldrine-Lakra** [comment]
Alright, I found a solution by using @teamwork/sharedb module with the @teamwork/sharedb-mongo adapter and my code works flawlessly

**Comment by alecgibson** [comment]
Assuming this is to do with the move to v3, which we're already addressing, so I'll close this to keep things tidy. Please feel free to open a new issue if you find anything else.
