### ISSUE TITLE
Mongo transactions using sharedb-mongo

### ISSUE THREAD

**Issue by vedadeepta** [share/sharedb-mongo#93]
How can mongodb transactions be done using this adapter for atomicity across documents?

https://docs.mongodb.com/manual/core/transactions/

**Comment by alecgibson** [comment]
What sort of use-case did you have in mind?

**Comment by vedadeepta** [comment]
Updating multiple docs but the updates needs to be atomic (e.g when deducting balance from user-A's account and adding it to user-B's account).

**Comment by alecgibson** [comment]
`sharedb-mongo` doesn't currently support Mongo v4's transactions. Depending on the level of atomicity you're happy with, you could potentially write middleware that catches both documents at their ShareDB `commit` hook, and ensures they're both ready to commit before committing.

However, this probably doesn't solve the exact problem you're looking to solve. To be honest, I'd query whether ShareDB is the right tool for this job. Its model is built more around decentralised writes, with clients almost writing directly to the database. What you're designing sounds like it wants strict marshalling, preferably through a tightly-controlled server that knows a lot about business logic (which is good to keep on your server, and not in clients, which you have less control over).

That being said, I'm sure it can be made to work if you want it to work this way, and Pull Requests are always welcome.
